### PR TITLE
fix a few security issues

### PR DESCRIPTION
**Pull request by rburgst**
- dont allow anonymous users to upload
- dont allow users to view other users orders
  (one could debate whether allowing someone else
   to pay for my order should be allowed or not)

### CODE REVIEW

**Comment by talmax1124** [comment]
@rburgst If you see the finished repository, These features are already implemented. Only people who have logged in can view, place an order, and so on. And admins are the only one who can see the upload images through the Product edit screen. Please delete this pull request since these features have already been implemented since the beginning.

**Comment by rburgst** [comment]
Hi, the fixes I have done are for the backend. Your current `master` does not contain backend protections for any authenticated user being able to view anyone elses orders as long as they have the order id.

Also if you check your uploadController you will find that there is no protection whatsoever, you can simply POST any image without authentication (note that I only changed the backend first and then could no longer upload images from the frontend, which proves that the `master` did not check any credentials for image uploads).

**Comment by basir** [comment]
> Hi, the fixes I have done are for the backend. Your current `master` does not contain backend protections for any authenticated user being able to view anyone elses orders as long as they have the order id.
> 
> Also if you check your uploadController you will find that there is no protection whatsoever, you can simply POST any image without authentication (note that I only changed the backend first and then could no longer upload images from the frontend, which proves that the `master` did not check any credentials for image uploads).

hello there
Thanks for the fixes.
I will apply them to the next update for the repository. Because we need to make a video for all bug fixes I can not merge it with the master but they have been noted for the next update.

**Comment by rburgst** [comment]
Any ETA on this?

**Pull request closed without merging**
